Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.2
    l2: 0.001
    nb_epoch: 1500
    nb_filter: 128
    lr: 0.01
    output1: 128
    output2: 128
  name: "Dog_1"
################################################
Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.3
    l2: 0.01
    nb_epoch: 6000
    nb_filter: 512
    lr: 0.005
    output1: 32
    output2: 32
  name: "Dog_2"
################################################
Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.9
    l2: 0.008
    nb_epoch: 900
    nb_filter: 64
    lr: 0.01
    output1: 64
    output2: 64
  name: "Dog_3"
################################################
Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.9
    l2: 0.002
    nb_epoch: 4200
    nb_filter: 32
    lr: 0.01
    output1: 64
    output2: 64
  name: "Dog_4"
################################################
Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.7
    l2: 0.001
    nb_epoch: 15000
    nb_filter: 128
    lr: 0.01
    output1: 128
    output2: 128
  name: "Dog_5"
################################################
Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.1
    l2: 0.001
    nb_epoch: 60000
    nb_filter: 64
    lr: 0.01
    output1: 16
    output2: 16
  name: "Patient_1"
################################################
Setting:
  DataProcess:
    resampleFrequency: 400
    bandNum: 8
    processedDataPath: "/home/xiaobin/trainData/"
    rawDataPath: "/home/xiaobin/raw_data/"
    savePath: "kaggleSolution/submissions/"
    splitNum: 10
    timeSlotLength: 60
    timeSlotNum: 10
  Model:
    batch_size: 128
    dropout: 0.3
    l2: 0.005
    nb_epoch: 200000
    nb_filter: 64
    lr: 0.01
    output1: 128
    output2: 128
  name: "Patient_2"
